### PR TITLE
GCC<6 fix, abort() fixes, code cleanup

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
The remaining two Travis failures are unrelated to my fix; one must have already been there before we even started fixing JasPer a few months ago. Both failures need GCC version checks.

**Comment by MaxKellermann** [comment]
Don't merge just yet - I need to fix a few compiler warnings.
Fixes for the build failures will also be added.

**Comment by MaxKellermann** [comment]
Fixed several issues in today's force-push, and added a bunch of new commits, including several bug fixes.

**Comment by MaxKellermann** [comment]
After some twiddling, I fixed the `tmpnam()`-related build failures with MSVC. I barely remembered how bad MSVC's C implementation was...

**Comment by MaxKellermann** [comment]
Added a bunch of optimizations which speed up `imginfo` by 8%.

**Comment by MaxKellermann** [comment]
Unit test failures - I dropped several patches until I have time to fix them.

**Comment by MaxKellermann** [comment]
The AppVeyor failure is a compiler bug. The Microsoft compiler does not implement C99 properly.

**Comment by jubalh** [comment]
>Don't merge just yet - I need to fix a few compiler warnings.

@MaxKellermann I'm going to merge this now, ok?

**Comment by MaxKellermann** [comment]
Yes, please.

**Pull request merged**
