### PR TITLE
Don't crash the application if ICC color profile is incorrect

### PR DESCRIPTION
**Pull request by theta682**
Incorrect ICC color profile should not kill the application.
Just report an issue and continue. It is not a critical issue.

### CODE REVIEW

**Comment by theta682** [comment]
@mdadams we have a file reported by a security researcher produced by fuzzing. It crashes the application by calling `abort()` in `icctoclrspc`. Incorrect ICC profile is not a critical issue. Even if it is `jasper` library should not kill the application.

**Comment by theta682** [comment]
[jp2k-incorrect-icc.jp2.zip](https://github.com/jasper-software/jasper/files/8810231/jp2k-incorrect-icc.jp2.zip) the file which kills the application

**Comment by theta682** [comment]
Related to #326

**Comment by theta682** [comment]
@mdadams can you release a new version with current fixes? In this case, we can switch our code to the official release and report to an external security researcher that the vulnerability is fixed in our product.

**Comment by mdadams** [comment]
@theta682  Sure, I'll make a new release.  I am just in the process of adding your JP2 image with a bad ICC profile to the test cases for JasPer.  I think that it would be a very good idea to have this image as a test case, since I don't think that any of the other test cases have this type of bad ICC profile.
Also, I went through all of the calls to the abort function that I could find in the JasPer code.  In the JasPer library, most of the calls to abort are trapping a fatal programming error or unrecoverable error (such as a failure in library initialization caused by a precondition violation).  Since people often compile with NDEBUG for release builds, I often use abort calls instead of an assert(0) for trapping fatal problems instead of having the code simply go off the deep end in a release build.  For example, I often place an abort call in parts of the code that should never be reached unless the code is insane (e.g., in the default clause of a switch when the non-default clauses should handle all of the possibilities).  There are a few abort calls in test code, but this is not in the library and therefore will not impact any users of the library.  There are a few places where I trap calls to unimplemented functions.  With the above said, I did find three functions that used abort (sometimes several times) when they really should not have: jas_image_chclrspc, bmp_numcmpts, and jas_stream_display.  I have fixed these functions now.  So, between your PR and my changes, I think that the library should be in reasonably good shape with respect to avoiding bogus abort calls. If you have any specific concerns about any of the remaining abort calls, please let me know.

**Comment by mdadams** [comment]
@theta682  A new release of JasPer has now been made (3.0.4), as requested.

**Pull request merged**
