### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by Jamaika1**

### CODE REVIEW

**Comment by mdadams** [comment]
@Jamaika1  I think that some old Windows systems may need the io.h check as it was before.  What is the motivation for the change?  Is the current code not building correctly on some platform, and if so, which one?

**Comment by Jamaika1** [comment]
You are the creator and you decide. I proposed this model in libheif. He passed the test and that's it. I don't know what the creator's intentions are. There was a suggestion to remove JAS_HAVE_IO_H.

**Comment by jubalh** [comment]
I would close this PR since @Jamaika1 can not name a reason for this change.
Feel free to reopen/merge if there is a reason provided and commit message contains a description.

**Comment by mdadams** [comment]
@jubalh I agree that we should not just change this only for the sake of change when no real problem exists, since any change has the potential to break the build for some platforms.

**Pull request closed without merging**
